### PR TITLE
Add Workshops

### PR DESCRIPTION
**Pull request by Davidovich4**
@daroczig

### CODE REVIEW

**Comment by daroczig** [comment]
This is great, thanks a lot! 

What's the order of workshop titles? Maybe let's order in ABC? Or maybe better to have this as a list by topic?

I'm really not sure what's the best way to render this, looking forward to any feedback

**Comment by Davidovich4** [comment]
I haven't thought about it, but you have a point. I would probably prefer **list by topic**.

**Comment by daroczig** [comment]
Yeah, same here.

Planning to announce this batch of great news on Wednesday after all -- will you have time to check how it looks like that way?

**Comment by Davidovich4** [comment]
Sure, I will have some time tomorrow.

Please let me know, if there is any other task that needs to ship with the wednesday batch

**Comment by daroczig** [comment]
The `Forwards Package Development Workshop for Women` workshop seems to be missing from the list?

**Comment by Davidovich4** [comment]
Indeed, sorry about that! Not sure how I skipped that record. (also missed
adding Isabelle to workshop tutors)

I am gonna fix it within an hour I think.

2018. febr. 6. du. 4:24 ezt írta ("Gergely Daróczi" <
notifications@github.com>):

**Comment by daroczig** [comment]
Awesome, thanks! And no rush, we won't merge & announce today

**Comment by Davidovich4** [comment]
Alright, just pushed the update.

ToDo:
- Trim workshop tutor titles. - Should we trim all to 2 lines? It's tough for a few persons.
- Format speaker bios (layout, links, etc)

**Comment by daroczig** [comment]
Thanks!

And another thing came to my mind: there are workshops with 2 speakers -- can you pls check those?

> Trim workshop tutor titles. - Should we trim all to 2 lines? It's tough for a few persons.

Yes. But I can do the trimming if you don't want to argue with the angry people :)

**Comment by Davidovich4** [comment]
And another thing came to my mind: there are workshops with 2 speakers --
can you pls check those?

Yeah, I am gonna take a look today.

Trim workshop tutor titles. - Should we trim all to 2 lines? It's tough for
a few persons.

Yes. But I can do the trimming if you don't want to argue with the angry
people :)

I would very much appreciate that, thanks! :)

**Comment by daroczig** [comment]
trimming done :+1: 

and sorry for the reindenting stuff, it's really hard to ask my emacs config not to enforce my code style

**Comment by daroczig** [comment]
re indenting -- I hope the above commit + http://editorconfig.org helps

**Comment by Davidovich4** [comment]
As for workshops with multiple speakers there are 2 thing to consider:
1. Speakers/Tutors list - In the `workshop tutors` section
2. Description of the workshop - In the `workshops` section

For the first, we should probably use the name of the organization instead of one speaker's name. e.g.: Mango Solutions, with the abstract containing the names of all the involved speakers.

For the second one, I am not entirely sure what would be the best:
1. List all speakers individually
2. Separate `individuals`, and `teams`. e.g.:

- Individuals
    - Speaker1
    - ...
- Teams
    - Team1
        - Speaker1
        - Speaker2 

3. List only the "team name":

- Speaker1
- Team1
- Speaker2


Other: I plan to format the bio of all the speakers: https://imgur.com/a/B5CvY.

What do you think?

**Comment by daroczig** [comment]
> As for workshops with multiple speakers there are 2 thing to consider:

Hm, good point. Maybe we simplify this by having only 1 column that includes the workshop title + speaker(s) as well, eg

```
Building a package that lasts by Colin Fay
```

This we we can just have the speakers as CSV.

> List all speakers individually

Sure, let's keep it simple -- this is fine.

> Other: I plan to format the bio of all the speakers: https://imgur.com/a/B5CvY.

This is very cool!!!

**Comment by Davidovich4** [comment]
> Hm, good point. Maybe we simplify this by having only 1 column that includes the workshop title + speaker(s) as well

I think we should list all authors in separate paragraphs. It's much easier to read. https://imgur.com/a/IFDSS

**Comment by daroczig** [comment]
> I think we should list all authors in separate paragraphs. It's much easier to read. https://imgur.com/a/IFDSS

Sounds very good to me :+1:

**Comment by Davidovich4** [comment]
Alright, I could figure out all the additional speakers that we need to add, except for the Mango workshop: `Deep Learning with Keras for R`.

The bio mentions Douglas and Mark. After some googling I found **Douglas Ashton** and **Mark Sellors**. Could you please confirm them with Aimee/Mango Solutions?

**Comment by daroczig** [comment]
Yeah, you are correct regarding the co-authors -- as per the `Coauthors` column of the spreadsheet :)

Ping me on slack if you need anything else, sending an invite

**Comment by Davidovich4** [comment]
Bah, completely missed that column, sorry about that... :)

**Comment by Davidovich4** [comment]
Done with adding co-authors as speakers.

- Issue: Can't find picture of Mateusz Staniak.

**Comment by daroczig** [comment]
@mstaniak can you please help us out with a profile photo? cc @pbiecek

**Comment by mstaniak** [comment]
Link to a photo: http://mi2.mini.pw.edu.pl/wp-content/uploads/2017/02/MStaniak.jpg

**Comment by daroczig** [comment]
@Davidovich4 -- I think we can merge & announce, agreed?

**Pull request merged**
