### PR TITLE
More speakers

### PR DESCRIPTION
**Pull request by Davidovich4**
Added all of the remaining speakers:

To do:
- Change/remove paragraphs in the new speaker sections
- Add missing speaker images. (I can't find them on the web. Can you please ask them to send an image?)

### CODE REVIEW

**Comment by daroczig** [comment]
Thanks a lot!
Can you pls add an empty/blank/white square image as a placeholder for the speakers without a profile photo?

**Comment by Davidovich4** [comment]
Done! Ping me, if it needs modification.

**Comment by daroczig** [comment]
This is great :+1: 

Let's remove the //TODO paragraphs (no need to add anything instead) and we can merge.

**Comment by Davidovich4** [comment]
it's done :+1:

**Pull request merged**
