### PR TITLE
Add available slides and videos

### PR DESCRIPTION
**Pull request by dgyurko**
Some issues:

- Florian Privé - No video, but we have a slide.
- Francesca Vitalini - Video is not in the playlist.
- Chris von Csefalvay - No slide, no video.
- Tajti András - No slide, no video.

### CODE REVIEW

**Comment by daroczig** [comment]
This is great, thanks a lot!

Chris and Andras did not present after all :/
Let's remove them from the program / schedule.

I'm checking on the missing 2 videos.

Meanwhile, can you please update this PR by making sure that the icons are aligned in the same way in each row? Eg let's have an empty cell for the slides if we do not have those to make the video icon stand in the far right column?

**Comment by dgyurko** [comment]
Good catch! I just fixed those problems, please check them out.

**Comment by daroczig** [comment]
Thanks a lot! Found some further keynote slides:

- Martin Maechler:: bit.ly/MM_eRum2018 
- Roger Bivand: https://github.com/rsbivand/eRum18

And a couple others as well as referenced in the below tweets:

- https://twitter.com/KKulma/status/996061486966628352
- https://twitter.com/_lionelhenry/status/996428514088964096
- https://twitter.com/_ColinFay/status/996050838845091841
- https://twitter.com/opencpu/status/996713681420513281
- https://twitter.com/HeathrTurnr/status/996632979282776066
- https://twitter.com/robinlovelace/status/996765479749464065
- https://twitter.com/olga_mie/status/996338792805093376
- https://twitter.com/petolauri/status/996466680376197125
- https://twitter.com/edwin_thoen/status/996320142870138880
- https://twitter.com/kosinski_rblog/status/996340257825214465
- https://twitter.com/ClausEkstrom/status/996716640426496001
- https://twitter.com/DataScienceLA/status/996378179827879936
- https://twitter.com/Fieldy6961/status/997119391262265346
- https://twitter.com/LubomirStepanek/status/997094436906598400
- https://twitter.com/GSMilovanovic/status/997046245452668928
- https://twitter.com/timothywong731/status/996936783593123840
- https://twitter.com/WitJakuczun/status/996763977966346241
- https://twitter.com/edwindjonge/status/996749209977131008
- https://twitter.com/aimeegott_R/status/996683485120204800
- https://twitter.com/freakonometrics/status/996682027817754625
- https://twitter.com/DataWookie/status/996422223845044225
- https://twitter.com/stadlmann_/status/996388873134583808
- https://twitter.com/ledell/status/996360349447270401
- https://twitter.com/DataScienceLA/status/999642075795673088
- https://twitter.com/dmi3k/status/996683375825113088

**Comment by dgyurko** [comment]
Done.

**Pull request merged**
